### ISSUE TITLE
Absolute path broke my environment.

### ISSUE THREAD

**Issue by egonzalf** [kaust-rc/modules-intel#1]
In setup.tcl, line 8, an absolute path is used instead of using KAUST_APPS_ROOT, that broke my module environment.
https://github.com/kaust-rc/modules-intel/blob/0c72281f2452f74197180d5c424f2bbe49039f9e/common/setup.tcl#L8

**Comment by sarahelhammadi** [comment]
@egonzalf Could you please elaborate more on how it broke your module environment and how to reproduce it?

**Comment by egonzalf** [comment]
Just mount the modules in a different path (rather than in /opt/share/) and the set the variables accordingly (KAUST_APPS_ROOT, KAUST_MODULES_ROOT and MODULESPATH)

**Comment by egonzalf** [comment]
@sarahelhammadi For example, I mounted it in /opt/wsintelapps,
```bash
export KAUST_APPS_ROOT=/opt/wsintelapps
export KAUST_MODULES_ROOT=/opt/wsintelapps/modules
export MODULEPATH=/opt/wsintelapps/modules/applications:/opt/wsintelapps/modules/compilers:/opt/wsintelapps/modules/libs:/opt/wsintelapps/modules/sets
$ module load intel/2017  
ModuleCmd_Use.c(231):ERROR:64: Directory '/opt/share/spack/share/spack/modules/linux-rhel6-x86_64' not found
intel/2017(3):ERROR:102: Tcl command execution failed: source $env(KAUST_MODULES_ROOT)/common/setup.tcl

```
